CREATE TABLE PROFESOR(
	NOMBRE VARCHAR(50),
	COD_PROF INTEGER(5),
	CONSTRAINT PK_1 PRIMARY KEY (COD_PROF)
);

CREATE TABLE MATERIA(
	ID INTEGER(4),
	CONSTRAINT PK_2 PRIMARY KEY (ID)
);

CREATE TABLE ESTUDIANTE(
	ID_ESTUDIANTE VARCHAR(20),
	NOMBRE VARCHAR(50),
	FECHA_NAC DATE,
	CORREO VARCHAR(30),
	CONSTRAINT PK_3 PRIMARY KEY (ID_ESTUDIANTE)
);

CREATE TABLE EXAMEN(
	FECHA_EX DATE,
	ASIGNATURA VARCHAR(20),
	ID_MATERIA INTEGER(4),
	CONSTRAINT PK_4 PRIMARY KEY (FECHA_EX),
	CONSTRAINT FK_1 FOREIGN KEY (ID_MATERIA) REFERENCES MATERIA(ID)
 );
 
CREATE TABLE PONE(
	COD_PROF INTEGER(5),
	FECHA_EX DATE,
	CONSTRAINT PK_5 PRIMARY KEY (COD_PROF, FECHA_EX),
	CONSTRAINT FK_2 FOREIGN KEY (COD_PROF) REFERENCES PROFESOR(COD_PROF),
	CONSTRAINT FK_3 FOREIGN KEY (FECHA_EX) REFERENCES EXAMEN(FECHA_EX)
);

CREATE TABLE IMPARTE(
	COD_PROF INTEGER(5),
	ID INTEGER(4),
	CONSTRAINT PK_5 PRIMARY KEY (COD_PROF,ID),
	CONSTRAINT FK_4 FOREIGN KEY (COD_PROF) REFERENCES PROFESOR(COD_PROF),
	CONSTRAINT FK_5 FOREIGN KEY (ID) REFERENCES MATERIA(ID)
);

CREATE TABLE APRENDE(
	ID INTEGER(4),
	ID_ESTUDIANTE VARCHAR(20),
	CONSTRAINT PK_6 PRIMARY KEY (ID, ID_ESTUDIANTE),
	CONSTRAINT FK_6 FOREIGN KEY (ID) REFERENCES MATERIA(ID),
	CONSTRAINT FK_7 FOREIGN KEY (ID_ESTUDIANTE) REFERENCES ESTUDIANTE(ID_ESTUDIANTE)
);

CREATE TABLE REALIZA(
	ID_ESTUDIANTE VARCHAR(20),
	FECHA_EX DATE,
	CONSTRAINT PK_7 PRIMARY KEY (FECHA_EX,ID_ESTUDIANTE),
	CONSTRAINT FK_8 FOREIGN KEY (ID_ESTUDIANTE) REFERENCES ESTUDIANTE(ID_ESTUDIANTE),
	CONSTRAINT FK_9 FOREIGN KEY (FECHA_EX) REFERENCES EXAMEN(FECHA_EX)
);